source 'https://rubygems.org'

gem 'autoprefixer-rails'
gem 'bootstrap-sass'
gem 'dotenv-rails'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'rails', '5.0.0.1'
gem 'sass-rails', '~> 5.0'
gem 'scrivito', '1.7.0.rc1'
gem 'scrivito_advanced_editors'
gem 'secure_headers'
gem 'uglifier'

ruby '2.3.1'